# Generated by Django 4.2.11 on 2024-04-26 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finlife', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositproducts',
            name='fin_prdt_cd',
            field=models.TextField(unique=True),
        ),
    ]
