# Generated by Django 4.2.11 on 2024-04-12 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('Comedy', 'Comedy'), ('Fantasy', 'Fantasy'), ('Romance', 'Romance')], max_length=50),
        ),
    ]
